# Generated by Django 2.0 on 2019-10-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_text', models.TextField(max_length=5000)),
                ('pub_date', models.DateField(verbose_name='date published')),
            ],
        ),
    ]
