# Generated by Django 2.0 on 2019-10-10 06:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
