# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-05 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('pwd', models.CharField(max_length=100)),
                ('nickname', models.CharField(default='匿名用户', max_length=100)),
                ('sex', models.CharField(default='男', max_length=100)),
                ('phone', models.CharField(default='110', max_length=100)),
                ('avatar', models.ImageField(default='static/user/avatar/default.jpg', upload_to='static/user/avatar')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='auth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
    ]
