# Generated by Django 2.0 on 2020-03-30 07:51

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='标识')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('content', tinymce.models.HTMLField(verbose_name='内容')),
                ('count', models.IntegerField(default=0, verbose_name='点击量')),
                ('publishtime', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
                ('modifytime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
        ),
        migrations.CreateModel(
            name='Expertdetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='标识')),
                ('name', models.CharField(max_length=255, null=True)),
                ('organization', models.CharField(max_length=200, null=True)),
                ('positionalitles', models.CharField(max_length=200, null=True)),
                ('abstract', models.TextField(null=True)),
                ('focusareas', models.CharField(max_length=1000, null=True)),
                ('fund', models.CharField(max_length=1000, null=True)),
                ('subjects', models.CharField(max_length=1000, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('tel', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255, null=True)),
                ('publishtime', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='标识')),
                ('title', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('area', models.CharField(max_length=255, null=True)),
                ('platform', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('web', models.CharField(max_length=255, null=True)),
                ('start_time', models.CharField(max_length=255, null=True)),
                ('state', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=255, null=True)),
                ('mail', models.CharField(max_length=255, null=True)),
                ('project', models.TextField(null=True)),
                ('finance', models.TextField(null=True)),
                ('introduction', models.TextField(null=True)),
                ('company', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='标识')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('age', models.IntegerField(default=18)),
                ('pwd', models.CharField(max_length=100)),
                ('nickname', models.CharField(default='匿名用户', max_length=100)),
                ('email', models.CharField(default='110@qq.com', max_length=100)),
                ('sex', models.CharField(default='男', max_length=100)),
                ('phone', models.CharField(default='110', max_length=100)),
                ('status', models.IntegerField(default=1, verbose_name='用户状态')),
                ('avatar', models.ImageField(default='static/user/avatar/default.jpg', upload_to='static/user/avatar')),
            ],
        ),
        migrations.AddField(
            model_name='judge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
        migrations.AddField(
            model_name='article',
            name='auth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='作者外键'),
        ),
    ]
