# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-06 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0002_auto_20181205_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=18, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='110@qq.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='发表时间'),
        ),
    ]
