# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-08 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0005_auto_20181207_2202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='time',
            new_name='publishtime',
        ),
        migrations.AddField(
            model_name='article',
            name='modifytime',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
    ]
