# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-08 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0006_auto_20181208_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='count',
            field=models.IntegerField(default=0, verbose_name='点击量'),
        ),
    ]
