# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-10 07:50
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0007_article_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.IntegerField(default=1, verbose_name='用户状态'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='内容'),
        ),
    ]
