# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-17 09:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0008_auto_20181210_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255, null=True)),
                ('publishtime', models.DateTimeField(auto_now_add=True)),
                ('aritle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
    ]
