# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-17 09:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0009_judge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='judge',
            old_name='aritle',
            new_name='aritcle',
        ),
    ]
