# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-17 09:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0010_auto_20181217_1750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='judge',
            old_name='aritcle',
            new_name='article',
        ),
    ]
