# Generated by Django 2.0 on 2019-08-19 02:16

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0011_auto_20181217_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='标识')),
                ('name', models.CharField(max_length=255, verbose_name='姓名')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('area', tinymce.models.HTMLField(verbose_name='地址')),
                ('major', tinymce.models.HTMLField(verbose_name='专业')),
                ('email', models.CharField(max_length=255, verbose_name='邮箱')),
                ('baseinfo', tinymce.models.HTMLField(verbose_name='基本信息')),
                ('paper', tinymce.models.HTMLField(verbose_name='论文')),
                ('project', tinymce.models.HTMLField(verbose_name='项目')),
                ('other', tinymce.models.HTMLField(verbose_name='其他')),
                ('publishtime', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
                ('modifytime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
        ),
    ]
