# Generated by Django 2.0 on 2019-08-19 02:23

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0012_peopleinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peopleinfo',
            name='area',
            field=tinymce.models.HTMLField(null=True, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='peopleinfo',
            name='baseinfo',
            field=tinymce.models.HTMLField(null=True, verbose_name='基本信息'),
        ),
        migrations.AlterField(
            model_name='peopleinfo',
            name='email',
            field=models.CharField(max_length=255, null=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='peopleinfo',
            name='major',
            field=tinymce.models.HTMLField(verbose_name='专业, null=True'),
        ),
        migrations.AlterField(
            model_name='peopleinfo',
            name='other',
            field=tinymce.models.HTMLField(null=True, verbose_name='其他'),
        ),
        migrations.AlterField(
            model_name='peopleinfo',
            name='paper',
            field=tinymce.models.HTMLField(null=True, verbose_name='论文'),
        ),
        migrations.AlterField(
            model_name='peopleinfo',
            name='project',
            field=tinymce.models.HTMLField(null=True, verbose_name='项目'),
        ),
        migrations.AlterField(
            model_name='peopleinfo',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name='标题'),
        ),
    ]
