# Generated by Django 2.0 on 2019-08-19 02:25

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0013_auto_20190819_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peopleinfo',
            name='major',
            field=tinymce.models.HTMLField(null=True, verbose_name='专业'),
        ),
    ]
