# Generated by Django 2.0 on 2019-08-19 02:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0014_auto_20190819_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peopleinfo',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='姓名'),
        ),
    ]
