# Generated by Django 2.0 on 2019-08-19 02:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0015_auto_20190819_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peopleinfo',
            name='modifytime',
        ),
        migrations.RemoveField(
            model_name='peopleinfo',
            name='publishtime',
        ),
        migrations.AlterField(
            model_name='peopleinfo',
            name='name',
            field=models.CharField(max_length=255, verbose_name='姓名'),
        ),
    ]
