# Generated by Django 2.0 on 2019-08-19 02:40

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0016_auto_20190819_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peopleinfo',
            name='area',
            field=tinymce.models.HTMLField(default='xxx', null=True, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='peopleinfo',
            name='baseinfo',
            field=tinymce.models.HTMLField(default='xxx', null=True, verbose_name='基本信息'),
        ),
        migrations.AlterField(
            model_name='peopleinfo',
            name='email',
            field=models.CharField(default='xxx', max_length=255, null=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='peopleinfo',
            name='major',
            field=tinymce.models.HTMLField(default='xxx', null=True, verbose_name='专业'),
        ),
        migrations.AlterField(
            model_name='peopleinfo',
            name='name',
            field=models.CharField(default='xxx', max_length=255, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='peopleinfo',
            name='other',
            field=tinymce.models.HTMLField(default='xxx', null=True, verbose_name='其他'),
        ),
        migrations.AlterField(
            model_name='peopleinfo',
            name='paper',
            field=tinymce.models.HTMLField(default='xxx', null=True, verbose_name='论文'),
        ),
        migrations.AlterField(
            model_name='peopleinfo',
            name='project',
            field=tinymce.models.HTMLField(default='xxx', null=True, verbose_name='项目'),
        ),
        migrations.AlterField(
            model_name='peopleinfo',
            name='title',
            field=models.CharField(default='xxx', max_length=255, null=True, verbose_name='标题'),
        ),
    ]
