# Generated by Django 2.0 on 2019-08-19 02:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0017_auto_20190819_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peopleinfo',
            name='area',
            field=models.CharField(default='xxx', max_length=100),
        ),
        migrations.AlterField(
            model_name='peopleinfo',
            name='baseinfo',
            field=models.CharField(default='xxx', max_length=255),
        ),
        migrations.AlterField(
            model_name='peopleinfo',
            name='email',
            field=models.CharField(default='xxx', max_length=255),
        ),
        migrations.AlterField(
            model_name='peopleinfo',
            name='major',
            field=models.CharField(default='xxx', max_length=100),
        ),
        migrations.AlterField(
            model_name='peopleinfo',
            name='name',
            field=models.CharField(max_length=255, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='peopleinfo',
            name='other',
            field=models.CharField(default='xxx', max_length=255),
        ),
        migrations.AlterField(
            model_name='peopleinfo',
            name='paper',
            field=models.CharField(default='xxx', max_length=255),
        ),
        migrations.AlterField(
            model_name='peopleinfo',
            name='project',
            field=models.CharField(default='xxx', max_length=255),
        ),
        migrations.AlterField(
            model_name='peopleinfo',
            name='title',
            field=models.CharField(default='xxx', max_length=255),
        ),
    ]
