# Generated by Django 2.0 on 2019-08-19 02:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0018_auto_20190819_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peopleinfo',
            name='name',
            field=models.CharField(default='xxx', max_length=255),
        ),
    ]
