# Generated by Django 2.0 on 2019-08-19 05:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0019_auto_20190819_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peopleinfo',
            name='area',
            field=models.CharField(default='xxx', max_length=255),
        ),
        migrations.AlterField(
            model_name='peopleinfo',
            name='baseinfo',
            field=models.TextField(default='xxx'),
        ),
        migrations.AlterField(
            model_name='peopleinfo',
            name='major',
            field=models.CharField(default='xxx', max_length=255),
        ),
        migrations.AlterField(
            model_name='peopleinfo',
            name='other',
            field=models.TextField(default='xxx'),
        ),
        migrations.AlterField(
            model_name='peopleinfo',
            name='paper',
            field=models.TextField(default='xxx'),
        ),
        migrations.AlterField(
            model_name='peopleinfo',
            name='project',
            field=models.TextField(default='xxx'),
        ),
    ]
