# Generated by Django 2.0 on 2019-08-19 06:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0020_auto_20190819_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peopleinfo',
            name='baseinfo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='peopleinfo',
            name='other',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='peopleinfo',
            name='paper',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='peopleinfo',
            name='project',
            field=models.TextField(),
        ),
    ]
