# Generated by Django 2.0 on 2019-08-20 07:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0021_auto_20190819_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='标识')),
                ('title', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('area', models.CharField(max_length=255, null=True)),
                ('platform', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('web', models.CharField(max_length=255, null=True)),
                ('start_time', models.CharField(max_length=255, null=True)),
                ('state', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=255, null=True)),
                ('mail', models.CharField(max_length=255, null=True)),
                ('project', models.TextField(null=True)),
                ('finance', models.TextField(null=True)),
                ('introduction', models.TextField(null=True)),
                ('company', models.TextField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PeopleInfo',
        ),
    ]
