# Generated by Django 2.0 on 2020-03-03 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='park_company_result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=55)),
                ('company_member', models.CharField(max_length=55)),
                ('company_area', models.CharField(max_length=55)),
                ('independent_1', models.CharField(max_length=55)),
                ('donate_1', models.CharField(max_length=55)),
                ('relation_1', models.CharField(max_length=55)),
                ('independent_2', models.CharField(max_length=55)),
                ('donate_2', models.CharField(max_length=55)),
                ('relation_2', models.CharField(max_length=55)),
                ('standard', models.CharField(max_length=55)),
                ('conversion', models.CharField(max_length=55)),
                ('system', models.CharField(max_length=55)),
                ('culture', models.CharField(max_length=55)),
                ('industry', models.CharField(max_length=55)),
                ('innovation', models.CharField(max_length=55)),
                ('proportion', models.CharField(max_length=55)),
                ('development', models.CharField(max_length=55)),
                ('sales_1', models.CharField(max_length=55)),
                ('sales_2', models.CharField(max_length=55)),
                ('sales_3', models.CharField(max_length=55)),
                ('assets_1', models.CharField(max_length=55)),
                ('assets_2', models.CharField(max_length=55)),
                ('assets_3', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='park_prize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=200)),
                ('big_detail', models.CharField(max_length=200)),
                ('company_member', models.CharField(max_length=200)),
                ('typee', models.CharField(max_length=200)),
                ('detail_type', models.CharField(max_length=200)),
                ('prize', models.CharField(max_length=200)),
                ('prize_money', models.CharField(max_length=200)),
                ('prize_attach', models.CharField(max_length=200)),
                ('prize_require', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='park_prize_result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=200)),
                ('big_detail', models.CharField(max_length=200)),
                ('company_member', models.CharField(max_length=200)),
                ('typee', models.CharField(max_length=200)),
                ('detail_type', models.CharField(max_length=200)),
                ('prize', models.CharField(max_length=200)),
                ('prize_money', models.CharField(max_length=200)),
                ('prize_attach', models.CharField(max_length=200)),
                ('prize_require', models.CharField(max_length=200)),
            ],
        ),
    ]
